version: '3.7'

services:
        petclinic:
                image: rajahamza104/spring-pet-clinic
                build: ./petclinic_automation_project/spring-petclinic-rest

        frontend:
                image: rajahamza104/spring-pet-clinic-front
                build: ./petclinic_automation_project/spring-petclinic-angular
                ports:
                        - '4200:4200'

