apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-angular
  labels:
    app: spring-petclinic-angular
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic-angular
  template:
    metadata:
      labels:
        app: spring-petclinic-angular
    spec:
      containers:
      - name: spring-petclinic-angular
        image: rajahamza104/frontend2
        ports:
        - name: http-port
          containerPort: 80
