apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-rest2
spec:
  selector:
    app: spring-petclinic-rest2
  ports: 
  - protocol: TCP
    port: 81
    targetPort: 9966
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-rest-cluster2
spec:
  selector:
    app: spring-petclinic-rest2
  ports:
  - protocol: TCP
    port: 9966
    targetPort: 9966
  type: ClusterIP


---

apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-angular-cluster2
spec:
  selector:
    app: spring-petclinic-angular2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-angular2
spec:
  selector:
    app: spring-petclinic-angular2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
